"""Add topic, difficulty, and time_limit_minutes to Test model

Revision ID: 5eecf5cc5f71
Revises: 2e20183101e5
Create Date: 2025-09-25 22:12:29.653606

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5eecf5cc5f71'
down_revision = '2e20183101e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('test_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.drop_column('difficulty')

    with op.batch_alter_table('test', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_limit_minutes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('topic', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('difficulty', sa.String(length=20), nullable=False))
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('difficulty')
        batch_op.drop_column('topic')
        batch_op.drop_column('time_limit_minutes')

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('difficulty', mysql.VARCHAR(length=20), nullable=True))
        batch_op.alter_column('test_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
