"""empty message

Revision ID: 951ab86a54ad
Revises: ddddf7942011
Create Date: 2025-09-22 13:41:28.770826

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '951ab86a54ad'
down_revision = 'ddddf7942011'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test', schema=None) as batch_op:
        batch_op.alter_column('creator_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test', schema=None) as batch_op:
        batch_op.alter_column('creator_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
